baseURL = 'https://marceloni.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'


googleAnalytics='G-EF75S6BMCD'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'Addons'
pageRef = '/categories/addon'
weight = 2

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 3

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 4

[taxonomies]
  tag = "tags"
  category = "categories"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
